### ISSUE TITLE
Problem in Fallout VR

### ISSUE THREAD

**Issue by Terenor** [ReaperAnon/CALIBER-Damage-Overhaul#1]
Hi, tried this one the first time for Fallout VR, i get this error:

SubrecordException Synthesis.esp => CALIBER_WeaponModificationPerk (000002:Synthesis.esp<Perk>) => PRKE: Did not have expected EPFB record to go with the EPFT record Mutagen.Bethesda.Plugins.Exceptions.MalformedDataException: Did not have expected EPFB record to go with the EPFT record
   at Mutagen.Bethesda.Fallout4.PerkBinaryCreateTranslation.ParseEffects(IMutagenReadStream stream)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mutagen.Bethesda.Fallout4.PerkBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, PreviousParse lastParsed, Dictionary`2 recordParseCount, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, TypedParseParams translationParams, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Fallout4.Fallout4ModMixIn.<>c__DisplayClass16_0.<EnumerateMajorRecords>b__0(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 299
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.RunProcessors(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Fallout4.Fallout4ModCommon.WriteParallel(IFallout4ModGetter item, MutagenWriter writer, BinaryWriteParameters param, ModKey modKey)
   at Mutagen.Bethesda.Fallout4.Fallout4ModBinaryWriteTranslation.Write(MutagenWriter writer, IFallout4ModGetter item, ModKey modKey, GroupMask importMask, BinaryWriteParameters param)
   at Mutagen.Bethesda.Fallout4.Fallout4ModBinaryTranslationMixIn.WriteToBinary(IFallout4ModGetter item, FilePath path, BinaryWriteParameters param, GroupMask importMask)
   at Mutagen.Bethesda.Fallout4.Fallout4ModBinaryOverlay.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinary(FilePath path, BinaryWriteParameters param)
   at Mutagen.Bethesda.Fallout4.Fallout4Mod.Fallout4WriteBuilderInstantiator.Write(IFallout4ModGetter mod, BinaryWriteBuilderParams`1 param)
   at Mutagen.Bethesda.Fallout4.Fallout4Mod.Fallout4WriteBuilderInstantiator.WriteAsync(IFallout4ModGetter mod, BinaryWriteBuilderParams`1 param)
   at Mutagen.Bethesda.Plugins.Binary.Translations.FileBinaryModdedWriteBuilder`1.WriteAsync()
   at Synthesis.Bethesda.Execution.Running.Runner.PostRunProcessor.Run(IGroupRun groupRun, ModPath path, IReadOnlySet`1 blackListMod) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\PostRunProcessor.cs:line 70
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 70
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 34
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 49
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Nullable`1 headerVersionOverride, FormIDRangeMode formIDRangeMode, Language targetLanguage, Boolean masterFile, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 53
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 209

**Comment by MapoTofu003** [comment]
I'm also getting a similar error for FO4 NG, non-VR

**Comment by hishykot** [comment]
Same exact thing! The version is 1.10.163.0.

**Comment by MapoTofu003** [comment]
Saw a solution in the discord support and got it working. Check that out guys. But I do hope this gets updated. Just in case, the discord link is in the Caliber Damage Description page

**Comment by hishykot** [comment]
Thank you so much!!!
